# Import packages and check versions

In [4]:
import tensorflow as tf

In [5]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


# Load a dataset

In [8]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build a ML model

In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2555836 , -0.0557938 , -0.25434518,  0.30628783, -0.26205862,
        -0.3033649 , -0.207808  , -0.13703921, -0.42244592,  0.700721  ]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.07970416, 0.09733042, 0.07980294, 0.13979727, 0.07918975,
        0.07598536, 0.0836045 , 0.08973547, 0.06745493, 0.20739526]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [18]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


# Train and evaluate model

In [19]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9174 - loss: 0.2895
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9578 - loss: 0.1414
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9677 - loss: 0.1062
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9736 - loss: 0.0868
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9757 - loss: 0.0746


In [20]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9776 - loss: 0.0719


[0.07193274796009064, 0.9775999784469604]

In [21]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [22]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.65971218e-08, 5.36420597e-09, 1.10406654e-06, 9.36474171e-05,
        9.23375872e-12, 3.53798498e-07, 4.85509549e-12, 9.99903202e-01,
        5.54370160e-07, 1.04297817e-06],
       [4.48595188e-07, 5.81774584e-05, 9.99939561e-01, 9.86164878e-07,
        1.17400068e-13, 8.64315197e-08, 3.52460205e-07, 6.04197551e-12,
        3.45085709e-07, 3.96758012e-13],
       [6.57981445e-07, 9.98575926e-01, 2.09899852e-04, 1.48441750e-05,
        1.45324275e-05, 2.50105059e-05, 1.68409260e-05, 1.10549189e-03,
        3.57346835e-05, 1.03895172e-06],
       [9.99986768e-01, 6.55803953e-11, 5.66647213e-06, 9.55399493e-09,
        1.17876496e-07, 8.26002520e-07, 1.58495641e-06, 2.25369786e-06,
        7.06245132e-11, 2.74311242e-06],
       [6.41630095e-06, 4.50013027e-10, 2.04845801e-05, 1.59613851e-08,
        9.99207914e-01, 8.71626696e-07, 3.53585665e-06, 8.56489260e-06,
        1.33066510e-06, 7.50885345e-04]], dtype=float32)>